version: "3.8"

services:
  app:
    image: shortlinks
    build: .
    environment:
      REDIS_URL: 'redis_db'
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app

  redis_db:
    build: ./docker/redis-cluster
    command: ["redis_cluster.conf"]
          
  redis_cluster2:
    build: ./docker/redis-cluster
    command: ["redis_cluster.conf"]

  redis_cluster3:
    build: ./docker/redis-cluster
    command: ["redis_cluster.conf"]

  redis_cluster4:
      build: ./docker/redis-cluster
      command: ["redis_cluster.conf"]

  redis_cluster5:
      build: ./docker/redis-cluster
      command: ["redis_cluster.conf"]

  redis_cluster6:
      build: ./docker/redis-cluster
      command: ["redis_cluster.conf"]        